"""Add download table

Revision ID: 27019706082b
Revises: 8b98fb25b5bf
Create Date: 2024-11-28 15:13:51.987132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '27019706082b'
down_revision: Union[str, None] = '8b98fb25b5bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.DateTime(), nullable=False),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('download')
    # ### end Alembic commands ###
