"""Replace automatic updated_at with manual imported_at

Revision ID: 47329e9404ef
Revises: a14164bdbf0d
Create Date: 2024-12-04 11:17:15.566158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47329e9404ef'
down_revision: Union[str, None] = 'a14164bdbf0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('download', sa.Column('imported_at', sa.DateTime(), nullable=False))
    op.drop_column('download', 'updated_at')
    op.drop_column('package', 'classifiers_array')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package', sa.Column('classifiers_array', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('download', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('download', 'imported_at')
    # ### end Alembic commands ###
