"""Make package name column unique

Revision ID: 60e7b8314b01
Revises: dd87d8a66a5e
Create Date: 2024-11-26 22:06:42.914349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '60e7b8314b01'
down_revision: Union[str, None] = 'dd87d8a66a5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'package', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'package', type_='unique')
    # ### end Alembic commands ###
