"""add classifier/package many-to-many relationship

Revision ID: 8b98fb25b5bf
Revises: f3311fd0ef3d
Create Date: 2024-11-27 13:08:58.112965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8b98fb25b5bf'
down_revision: Union[str, None] = 'f3311fd0ef3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classifier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classifier_name'), 'classifier', ['name'], unique=False)
    op.create_table('classifierpackagelink',
    sa.Column('classifier_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classifier_id'], ['classifier.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['package.id'], ),
    sa.PrimaryKeyConstraint('classifier_id', 'package_id')
    )
    op.drop_index('ix_package_name', table_name='package')
    op.create_index(op.f('ix_package_name'), 'package', ['name'], unique=False)
    # ### end Alembic commands ###




def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_package_name'), table_name='package')
    op.create_index('ix_package_name', 'package', ['name'], unique=True)
    op.drop_table('classifierpackagelink')
    op.drop_index(op.f('ix_classifier_name'), table_name='classifier')
    op.drop_table('classifier')
    # ### end Alembic commands ###
