"""Add package table

Revision ID: dd87d8a66a5e
Revises: 
Create Date: 2024-11-26 19:07:52.067121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dd87d8a66a5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('package',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metadata_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('maintainer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('maintainer_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('license', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('classifiers', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('platform', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('home_page', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('download_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('requires_python', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('requires', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('provides', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('obsoletes', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('requires_dist', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('provides_dist', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('obsoletes_dist', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('requires_external', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('project_urls', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('uploaded_via', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('upload_time', sa.DateTime(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('python_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('packagetype', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('comment_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('has_signature', sa.Boolean(), nullable=True),
    sa.Column('md5_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sha256_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('blake2_256_digest', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('license_expression', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('license_files', sa.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('package')
    # ### end Alembic commands ###
