"""Add index on package.name

Revision ID: f1ed49b3bdc5
Revises: 60e7b8314b01
Create Date: 2024-11-26 22:58:49.377994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f1ed49b3bdc5'
down_revision: Union[str, None] = '60e7b8314b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('package_name_key', 'package', type_='unique')
    op.create_index(op.f('ix_package_name'), 'package', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_package_name'), table_name='package')
    op.create_unique_constraint('package_name_key', 'package', ['name'])
    # ### end Alembic commands ###
